---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: jacobcarlborg/docker-alpine-wget
    tag: 'latest'

inputs:
   - name: pipeline-config
   
run:
  path: sh
  args: ["./pipeline-config/configure-pipelines.sh"]
