---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: troykinsella/concourse-fly-resource
    tag: 'latest'

inputs:
   - name: pipeline-config
   
run:
  path: sh
  args: ["configure-pipelines.sh"]
